In [1]:
import os, math, subprocess
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# some settings for displaying Pandas results
pd.set_option('display.width', 2000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.precision', 4)
pd.set_option('display.max_colwidth', 200)
pd.set_option('display.max_colwidth', -1)

# Load data and exploring statistics

In [2]:
!ls -lah home-credit-default-risk/

total 2.5G
drwxrwsr-x 2 hong ubuntu 4.0K Apr 16 16:38 .
drwxrwsr-x 4 hong ubuntu 4.0K Apr 16 16:39 ..
-rw-rw-r-- 1 hong ubuntu  26M Jun 26  2018 application_test.csv
-rw-rw-r-- 1 hong ubuntu 159M Jun 26  2018 application_train.csv
-rw-rw-r-- 1 hong ubuntu 359M Jun 26  2018 bureau_balance.csv
-rw-rw-r-- 1 hong ubuntu 163M Jun 26  2018 bureau.csv
-rw-rw-r-- 1 hong ubuntu 405M Jun 26  2018 credit_card_balance.csv
-rw-rw-r-- 1 hong ubuntu  37K Jun 26  2018 HomeCredit_columns_description.csv
-rw-rw-r-- 1 hong ubuntu 690M Jun 26  2018 installments_payments.csv
-rw-rw-r-- 1 hong ubuntu 375M Jun 26  2018 POS_CASH_balance.csv
-rw-rw-r-- 1 hong ubuntu 387M Jun 26  2018 previous_application.csv
-rw-rw-r-- 1 hong ubuntu 524K Jun 26  2018 sample_submission.csv

In [3]:
ls_files = subprocess.check_output(["ls", "-lah", "home-credit-default-risk/"]).decode("utf-8").splitlines()[3:]
ls_files = [f.split()[-1] for f in ls_files]
ls_files = sorted([f for f in ls_files if f not in ["HomeCredit_columns_description.csv"]])
ls_files

[u'POS_CASH_balance.csv',
 u'application_test.csv',
 u'application_train.csv',
 u'bureau.csv',
 u'bureau_balance.csv',
 u'credit_card_balance.csv',
 u'installments_payments.csv',
 u'previous_application.csv',
 u'sample_submission.csv']

In [4]:
def exploring_stats(pdf_input):
    # check rows, cols
    total_records = pdf_input.shape[0]
    total_columns = pdf_input.shape[1]
    print("Total records:", total_records)
    print("Total columns:", total_columns)

    # check dtypes
    name = []
    sub_type = []
    for n, t in pdf_input.dtypes.iteritems():
        name.append(n)
        sub_type.append(t)

    # check distinct
    ls_ndist = []
    for cname in pdf_input.columns:
        ndist = pdf_input[cname].nunique()
        pct_dist = ndist * 100.0 / total_records
        ls_ndist.append("{} ({:0.2f}%)".format(ndist, pct_dist))

    # check missing
    ls_nmiss = []
    for cname in pdf_input.columns:
        nmiss = pdf_input[cname].isnull().sum()
        pct_miss = nmiss * 100.0 / total_records
        ls_nmiss.append("{} ({:0.2f}%)".format(nmiss, pct_miss))

    # check zeros
    ls_zeros = []
    for cname in pdf_input.columns:
        try:
            nzeros = (pdf_input[cname] == 0).sum()
            pct_zeros = nzeros * 100.0 / total_records
            ls_zeros.append("{} ({:0.2f}%)".format(nzeros, pct_zeros))
        except:
            ls_zeros.append("{} ({:0.2f}%)".format(0, 0))
            continue

    # check negative
    ls_neg = []
    for cname in pdf_input.columns:
        try:
            nneg = (pdf_input[cname].astype("float") < 0).sum()
            pct_neg = nneg * 100.0 / total_records
            ls_neg.append("{} ({:0.2f}%)".format(nneg, pct_neg))
        except:
            ls_neg.append("{} ({:0.2f}%)".format(0, 0))
            continue

    # prepare output
    data = {
        "name": name,
        "sub_type": sub_type,
        "n_distinct": ls_ndist,
        "n_miss": ls_nmiss,
        "n_zeros": ls_zeros,
        "n_negative": ls_neg,
    }

    # check stats
    pdf_stats = pdf_input.describe().transpose()
    ls_stats = []
    for stat in pdf_stats.columns:
        data[stat] = []
        for cname in pdf_input.columns:
            try:
                data[stat].append(pdf_stats.loc[cname, stat])
            except:
                data[stat].append(0.0)

    # take samples
    nsample = 10
    pdf_sample = pdf_input.sample(frac=.5).head(nsample).transpose()
    pdf_sample.columns = ["sample_{}".format(i) for i in range(nsample)]

    # output
    col_ordered = ["sub_type", "n_distinct", "n_miss", "n_negative", "n_zeros",
                   "25%", "50%", "75%", "count", "max", "mean", "min", "std"] + list(pdf_sample.columns)
    pdf_data = pd.DataFrame(data).set_index("name")
    pdf_data = pd.concat([pdf_data, pdf_sample], axis=1)
    pdf_data = pdf_data[col_ordered]

    return pdf_data

In [5]:
%%time
ls_report = {}
for f in ls_files:
    print("Exploring {}".format(f))
    data_path = os.path.join("home-credit-default-risk", f)
    pdf_data = pd.read_csv(data_path)
    ls_report[f] = exploring_stats(pdf_data)
    display(ls_report[f])

Exploring POS_CASH_balance.csv
('Total records:', 10001358)
('Total columns:', 8)

                      sub_type      n_distinct         n_miss          n_negative           n_zeros        25%        50%        75%       count        max        mean        min          std sample_0 sample_1 sample_2 sample_3 sample_4 sample_5 sample_6 sample_7 sample_8 sample_9
name
SK_ID_PREV             int64    936325 (9.36%)  0 (0.00%)      0 (0.00%)           0 (0.00%)         1434405.0  1896565.0  2368963.0  1.0001e+07  2843499.0  1.9032e+06  1000001.0  535846.5307  2749119  1439762  2404083  1417828  1975679  2465369  2059772  1570568  2313395  2556181
SK_ID_CURR             int64    337252 (3.37%)  0 (0.00%)      0 (0.00%)           0 (0.00%)         189550.0   278654.0   367429.0   1.0001e+07  456255.0   2.7840e+05  100001.0   102763.7451  136725   412165   394468   230896   290188   301648   415723   432016   154158   280427
MONTHS_BALANCE         int64    96 (0.00%)      0 (0.00%)      10001358 (100.00%)  0 (0.00%)        -54.0      -28.0      -13.0       1.0001e+07 -1.0       -3.5013e+01 -96.0       26.0666      -40      -11      -24      -6       -63      -12      -2       -92      -21      -22
CNT_INSTALMENT         float64  73 (0.00%)      26071 (0.26%)  0 (0.00%)           0 (0.00%)         10.0       12.0       24.0       9.9753e+06  92.0       1.7090e+01  1.0        11.9951      12       12       10       8        10       36       12       10       60       18
CNT_INSTALMENT_FUTURE  float64  79 (0.00%)      26087 (0.26%)  0 (0.00%)           1185960 (11.86%)  3.0        7.0        14.0       9.9753e+06  85.0       1.0484e+01  0.0        11.1091      1        3        10       8        1        17       1        10       51       17
NAME_CONTRACT_STATUS   object   9 (0.00%)       0 (0.00%)      0 (0.00%)           0 (0.00%)         0.0        0.0        0.0        0.0000e+00  0.0        0.0000e+00  0.0        0.0000       Active   Active   Active   Active   Active   Active   Active   Active   Active   Active
SK_DPD                 int64    3400 (0.03%)    0 (0.00%)      0 (0.00%)           9706131 (97.05%)  0.0        0.0        0.0        1.0001e+07  4231.0     1.1607e+01  0.0        132.7140     0        0        0        0        0        0        0        0        0        0
SK_DPD_DEF             int64    2307 (0.02%)    0 (0.00%)      0 (0.00%)           9887389 (98.86%)  0.0        0.0        0.0        1.0001e+07  3595.0     6.5447e-01  0.0        32.7625      0        0        0        0        0        0        0        0        0        0

Exploring application_test.csv
('Total records:', 48744)
('Total columns:', 121)

                             sub_type       n_distinct          n_miss       n_negative          n_zeros          25%          50%          75%    count         max        mean         min          std                       sample_0              sample_1           sample_2                sample_3                       sample_4                       sample_5                       sample_6                       sample_7                       sample_8                       sample_9
name
SK_ID_CURR                    int64    48744 (100.00%)  0 (0.00%)       0 (0.00%)        0 (0.00%)        188557.7500  277549.0000  367555.5000  48744.0  4.5625e+05  2.7780e+05  1.0000e+05  103169.5473  413769                         267284                260484             359319                  152020                         211553                         183878                         303497                         285833                         261749
NAME_CONTRACT_TYPE            object   2 (0.00%)        0 (0.00%)       0 (0.00%)        0 (0.00%)        0.0000       0.0000       0.0000       0.0      0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Cash loans                     Cash loans            Cash loans         Cash loans              Cash loans                     Cash loans                     Cash loans                     Cash loans                     Cash loans                     Cash loans
CODE_GENDER                   object   2 (0.00%)        0 (0.00%)       0 (0.00%)        0 (0.00%)        0.0000       0.0000       0.0000       0.0      0.0000e+00  0.0000e+00  0.0000e+00  0.0000       F                              F                     F                  F                       F                              M                              F                              M                              F                              F
FLAG_OWN_CAR                  object   2 (0.00%)        0 (0.00%)       0 (0.00%)        0 (0.00%)        0.0000       0.0000       0.0000       0.0      0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Y                              N                     N                  N                       N                              N                              Y                              Y                              N                              N
FLAG_OWN_REALTY               object   2 (0.00%)        0 (0.00%)       0 (0.00%)        0 (0.00%)        0.0000       0.0000       0.0000       0.0      0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Y                              N                     Y                  N                       N                              N                              N                              Y                              N                              Y
CNT_CHILDREN                  int64    11 (0.02%)       0 (0.00%)       0 (0.00%)        34685 (71.16%)   0.0000       0.0000       1.0000       48744.0  2.0000e+01  3.9705e-01  0.0000e+00  0.7090       0                              0                     0                  0                       0                              0                              0                              1                              0                              0
AMT_INCOME_TOTAL              float64  606 (1.24%)      0 (0.00%)       0 (0.00%)        0 (0.00%)        112500.0000  157500.0000  225000.0000  48744.0  4.4100e+06  1.7843e+05  2.6942e+04  101522.5915  1.125e+05                      9e+04                 3.375e+05          1.8e+05                 9e+04                          1.35e+05                       1.125e+05                      2.475e+05                      6.75e+04                       8.1e+04
AMT_CREDIT                    float64  2937 (6.03%)     0 (0.00%)       0 (0.00%)        0 (0.00%)        260640.0000  450000.0000  675000.0000  48744.0  2.2455e+06  5.1674e+05  4.5000e+04  365397.0042  3.769e+05                      2.725e+05             1.305e+06          3.6e+05                 2.37e+05                       2.7e+05                        6.75e+05                       3.820e+05                      6.75e+05                       3.644e+05
AMT_ANNUITY                   float64  7491 (15.37%)    24 (0.05%)      0 (0.00%)        0 (0.00%)        17973.0000   26199.0000   37390.5000   48720.0  1.8058e+05  2.9426e+04  2.2950e+03  16016.3683   1.937e+04                      2.166e+04             4.21e+04           2.202e+04               1.528e+04                      2.476e+04                      3.46e+04                       2.35e+04                       2.545e+04                      1.545e+04
AMT_GOODS_PRICE               float64  677 (1.39%)      0 (0.00%)       0 (0.00%)        0 (0.00%)        225000.0000  396000.0000  630000.0000  48744.0  2.2455e+06  4.6262e+05  4.5000e+04  336710.2150  2.7e+05                        2.25e+05              1.305e+06          3.6e+05                 1.8e+05                        2.7e+05                        6.75e+05                       3.375e+05                      6.75e+05                       2.385e+05
NAME_TYPE_SUITE               object   7 (0.01%)        911 (1.87%)     0 (0.00%)        0 (0.00%)        0.0000       0.0000       0.0000       0.0      0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Unaccompanied                  Unaccompanied         Unaccompanied      Unaccompanied           Unaccompanied                  Unaccompanied                  Unaccompanied                  Unaccompanied                  Unaccompanied                  Unaccompanied
NAME_INCOME_TYPE              object   7 (0.01%)        0 (0.00%)       0 (0.00%)        0 (0.00%)        0.0000       0.0000       0.0000       0.0      0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Commercial associate           Working               State servant      Working                 Working                        Working                        Working                        Commercial associate           Pensioner                      Commercial associate
NAME_EDUCATION_TYPE           object   5 (0.01%)        0 (0.00%)       0 (0.00%)        0 (0.00%)        0.0000       0.0000       0.0000       0.0      0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Secondary / secondary special  Higher education      Higher education   Higher education        Secondary / secondary special  Secondary / secondary special  Secondary / secondary special  Secondary / secondary special  Secondary / secondary special  Secondary / secondary special
NAME_FAMILY_STATUS            object   5 (0.01%)        0 (0.00%)       0 (0.00%)        0 (0.00%)        0.0000       0.0000       0.0000       0.0      0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Married                        Single / not married  Married            Single / not married    Civil marriage                 Single / not married           Married                        Married                        Married                        Single / not married
NAME_HOUSING_TYPE             object   6 (0.01%)        0 (0.00%)       0 (0.00%)        0 (0.00%)        0.0000       0.0000       0.0000       0.0      0.0000e+00  0.0000e+00  0.0000e+00  0.0000       House / apartment              House / apartment     House / apartment  House / apartment       House / apartment              House / apartment              House / apartment              Office apartment               House / apartment              House / apartment
REGION_POPULATION_RELATIVE    float64  81 (0.17%)       0 (0.00%)       0 (0.00%)        0 (0.00%)        0.0100       0.0188       0.0287       48744.0  7.2508e-02  2.1226e-02  2.5300e-04  0.0144       0.00702                        0.00702               0.01821            0.03133                 0.04622                        0.01028                        0.02866                        0.01661                        0.01885                        0.01969
DAYS_BIRTH                    int64    15477 (31.75%)   0 (0.00%)       48744 (100.00%)  0 (0.00%)       -19637.0000  -15785.0000  -12496.0000   48744.0 -7.3380e+03 -1.6068e+04 -2.5195e+04  4325.9004    -13446                         -13328                -13049             -22112                  -14100                         -10439                         -19194                         -17876                         -19439                         -18497
DAYS_EMPLOYED                 int64    7863 (16.13%)    0 (0.00%)       39470 (80.97%)   0 (0.00%)       -2910.0000   -1293.0000   -296.0000     48744.0  3.6524e+05  6.7485e+04 -1.7463e+04  144348.5071  -1526                          -1264                 -4642              -1423                   -129                           -644                           -5185                          -1054                          365243                         -2819
DAYS_REGISTRATION             float64  12618 (25.89%)   0 (0.00%)       48731 (99.97%)   13 (0.03%)      -7459.2500   -4490.0000   -1901.0000    48744.0  0.0000e+00 -4.9677e+03 -2.3722e+04  3552.6120   -3286                          -9276                 -1224              -9655                   -8233                          -6015                          -4543                          -608                           -9630                          -2260
DAYS_ID_PUBLISH               int64    5880 (12.06%)    0 (0.00%)       48739 (99.99%)   5 (0.01%)       -4448.0000   -3234.0000   -1706.0000    48744.0  0.0000e+00 -3.0517e+03 -6.3480e+03  1569.2767    -3524                          -4381                 -4892              -4513                   -4191                          -2997                          -2734                          -1421                          -2991                          -2028
OWN_CAR_AGE                   float64  52 (0.11%)       32312 (66.29%)  0 (0.00%)        118 (0.24%)      4.0000       9.0000       15.0000      16432.0  7.4000e+01  1.1786e+01  0.0000e+00  11.4629      10                             NaN                   NaN                NaN                     NaN                            NaN                            17                             6                              NaN                            NaN
FLAG_MOBIL                    int64    2 (0.00%)        0 (0.00%)       0 (0.00%)        1 (0.00%)        1.0000       1.0000       1.0000       48744.0  1.0000e+00  9.9998e-01  0.0000e+00  0.0045       1                              1                     1                  1                       1                              1                              1                              1                              1                              1
FLAG_EMP_PHONE                int64    2 (0.00%)        0 (0.00%)       0 (0.00%)        9275 (19.03%)    1.0000       1.0000       1.0000       48744.0  1.0000e+00  8.0972e-01  0.0000e+00  0.3925       1                              1                     1                  1                       1                              1                              1                              1                              0                              1
FLAG_WORK_PHONE               int64    2 (0.00%)        0 (0.00%)       0 (0.00%)        38766 (79.53%)   0.0000       0.0000       0.0000       48744.0  1.0000e+00  2.0470e-01  0.0000e+00  0.4035       0                              0                     1                  1                       1                              0                              0                              0                              0                              1
FLAG_CONT_MOBILE              int64    2 (0.00%)        0 (0.00%)       0 (0.00%)        78 (0.16%)       1.0000       1.0000       1.0000       48744.0  1.0000e+00  9.9840e-01  0.0000e+00  0.0400       1                              1                     1                  1                       1                              1                              1                              1                              1                              1
FLAG_PHONE                    int64    2 (0.00%)        0 (0.00%)       0 (0.00%)        35918 (73.69%)   0.0000       0.0000       1.0000       48744.0  1.0000e+00  2.6313e-01  0.0000e+00  0.4403       0                              0                     1                  0                       0                              0                              1                              0                              1                              0
FLAG_EMAIL                    int64    2 (0.00%)        0 (0.00%)       0 (0.00%)        40816 (83.74%)   0.0000       0.0000       0.0000       48744.0  1.0000e+00  1.6265e-01  0.0000e+00  0.3690       0                              0                     0                  0                       0                              0                              0                              0                              0                              0
OCCUPATION_TYPE               object   18 (0.04%)       15605 (32.01%)  0 (0.00%)        0 (0.00%)        0.0000       0.0000       0.0000       0.0      0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Laborers                       Sales staff           Core staff         Medicine staff          Laborers                       Laborers                       Accountants                    Drivers                        NaN                            Cleaning staff
CNT_FAM_MEMBERS               float64  12 (0.02%)       0 (0.00%)       0 (0.00%)        0 (0.00%)        2.0000       2.0000       3.0000       48744.0  2.1000e+01  2.1468e+00  1.0000e+00  0.8904       2                              1                     2                  1                       2                              1                              2                              3                              2                              1
REGION_RATING_CLIENT          int64    3 (0.01%)        0 (0.00%)       0 (0.00%)        0 (0.00%)        2.0000       2.0000       2.0000       48744.0  3.0000e+00  2.0382e+00  1.0000e+00  0.5227       2                              2                     3                  2                       1                              2                              2                              2                              2                              2
REGION_RATING_CLIENT_W_CITY   int64    4 (0.01%)        0 (0.00%)       1 (0.00%)        0 (0.00%)        2.0000       2.0000       2.0000       48744.0  3.0000e+00  2.0126e+00 -1.0000e+00  0.5158       2                              2                     3                  2                       1                              2                              2                              2                              2                              2
WEEKDAY_APPR_PROCESS_START    object   7 (0.01%)        0 (0.00%)       0 (0.00%)        0 (0.00%)        0.0000       0.0000       0.0000       0.0      0.0000e+00  0.0000e+00  0.0000e+00  0.0000       FRIDAY                         THURSDAY              MONDAY             MONDAY                  SUNDAY                         THURSDAY                       WEDNESDAY                      THURSDAY                       TUESDAY                        THURSDAY
HOUR_APPR_PROCESS_START       int64    24 (0.05%)       0 (0.00%)       0 (0.00%)        8 (0.02%)        10.0000      12.0000      14.0000      48744.0  2.3000e+01  1.2007e+01  0.0000e+00  3.2782       16                             17                    11                 9                       14                             9                              11                             18                             12                             11
REG_REGION_NOT_LIVE_REGION    int64    2 (0.00%)        0 (0.00%)       0 (0.00%)        47826 (98.12%)   0.0000       0.0000       0.0000       48744.0  1.0000e+00  1.8833e-02  0.0000e+00  0.1359       0                              0                     0                  0                       0                              0                              0                              0                              0                              0
REG_REGION_NOT_WORK_REGION    int64    2 (0.00%)        0 (0.00%)       0 (0.00%)        46055 (94.48%)   0.0000       0.0000       0.0000       48744.0  1.0000e+00  5.5166e-02  0.0000e+00  0.2283       0                              0                     0                  0                       1                              0                              0                              0                              0                              0
LIVE_REGION_NOT_WORK_REGION   int64    2 (0.00%)        0 (0.00%)       0 (0.00%)        46695 (95.80%)   0.0000       0.0000       0.0000       48744.0  1.0000e+00  4.2036e-02  0.0000e+00  0.2007       0                              0                     0                  0                       1                              0                              0                              0                              0                              0
REG_CITY_NOT_LIVE_CITY        int64    2 (0.00%)        0 (0.00%)       0 (0.00%)        44968 (92.25%)   0.0000       0.0000       0.0000       48744.0  1.0000e+00  7.7466e-02  0.0000e+00  0.2673       0                              1                     0                  1                       0                              0                              0                              0                              0                              0
REG_CITY_NOT_WORK_CITY        int64    2 (0.00%)        0 (0.00%)       0 (0.00%)        37793 (77.53%)   0.0000       0.0000       0.0000       48744.0  1.0000e+00  2.2466e-01  0.0000e+00  0.4174       1                              1                     0                  1                       1                              1                              1                              0                              0                              0
LIVE_CITY_NOT_WORK_CITY       int64    2 (0.00%)        0 (0.00%)       0 (0.00%)        40252 (82.58%)   0.0000       0.0000       0.0000       48744.0  1.0000e+00  1.7422e-01  0.0000e+00  0.3793       1                              0                     0                  0                       1                              1                              1                              0                              0                              0
ORGANIZATION_TYPE             object   58 (0.12%)       0 (0.00%)       0 (0.00%)        0 (0.00%)        0.0000       0.0000       0.0000       0.0      0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Construction                   Self-employed         School             Business Entity Type 3  Business Entity Type 3         Business Entity Type 3         Business Entity Type 3         Self-employed                  XNA                            Trade: type 7
EXT_SOURCE_1                  float64  27207 (55.82%)   20532 (42.12%)  0 (0.00%)        0 (0.00%)        0.3437       0.5068       0.6660       28212.0  9.3914e-01  5.0118e-01  1.3458e-02  0.2051       0.4513                         0.02673               0.5048             NaN                     NaN                            0.1791                         0.582                          0.2933                         NaN                            NaN
EXT_SOURCE_2                  float64  38885 (79.77%)   8 (0.02%)       0 (0.00%)        0 (0.00%)        0.4081       0.5588       0.6585       48736.0  8.5500e-01  5.1802e-01  8.0979e-06  0.1813       0.4726                         0.05605               0.4092             0.5969                  0.4997                         0.4574                         0.5786                         0.395                          0.692                          0.07601

Exploring application_train.csv
('Total records:', 307511)
('Total columns:', 122)

                             sub_type        n_distinct           n_miss        n_negative           n_zeros          25%          50%          75%     count         max        mean         min          std                sample_0                sample_1                       sample_2                       sample_3                       sample_4                       sample_5                       sample_6                       sample_7                       sample_8                       sample_9
name
SK_ID_CURR                    int64    307511 (100.00%)  0 (0.00%)        0 (0.00%)         0 (0.00%)         189145.5000  278202.0000  367142.5000  307511.0  4.5626e+05  2.7818e+05  1.0000e+05  102790.1753  326682                  414578                  432657                         346257                         169928                         228494                         305986                         450918                         393627                         121604
TARGET                        int64    2 (0.00%)         0 (0.00%)        0 (0.00%)         282686 (91.93%)   0.0000       0.0000       0.0000       307511.0  1.0000e+00  8.0729e-02  0.0000e+00  0.2724       0                       1                       0                              0                              1                              0                              0                              1                              0                              0
NAME_CONTRACT_TYPE            object   2 (0.00%)         0 (0.00%)        0 (0.00%)         0 (0.00%)         0.0000       0.0000       0.0000       0.0       0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Cash loans              Cash loans              Revolving loans                Cash loans                     Cash loans                     Cash loans                     Cash loans                     Cash loans                     Cash loans                     Cash loans
CODE_GENDER                   object   3 (0.00%)         0 (0.00%)        0 (0.00%)         0 (0.00%)         0.0000       0.0000       0.0000       0.0       0.0000e+00  0.0000e+00  0.0000e+00  0.0000       M                       M                       M                              M                              M                              F                              M                              F                              F                              F
FLAG_OWN_CAR                  object   2 (0.00%)         0 (0.00%)        0 (0.00%)         0 (0.00%)         0.0000       0.0000       0.0000       0.0       0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Y                       Y                       N                              N                              N                              N                              N                              Y                              N                              N
FLAG_OWN_REALTY               object   2 (0.00%)         0 (0.00%)        0 (0.00%)         0 (0.00%)         0.0000       0.0000       0.0000       0.0       0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Y                       N                       Y                              Y                              Y                              Y                              Y                              N                              Y                              Y
CNT_CHILDREN                  int64    15 (0.00%)        0 (0.00%)        0 (0.00%)         215371 (70.04%)   0.0000       0.0000       1.0000       307511.0  1.9000e+01  4.1705e-01  0.0000e+00  0.7221       0                       1                       0                              0                              0                              0                              0                              1                              2                              0
AMT_INCOME_TOTAL              float64  2548 (0.83%)      0 (0.00%)        0 (0.00%)         0 (0.00%)         112500.0000  147150.0000  202500.0000  307511.0  1.1700e+08  1.6880e+05  2.5650e+04  237123.1463  1.665e+05               4.5e+05                 1.575e+05                      1.35e+05                       2.025e+05                      1.17e+05                       9e+04                          1.8e+05                        1.575e+05                      9e+04
AMT_CREDIT                    float64  5603 (1.82%)      0 (0.00%)        0 (0.00%)         0 (0.00%)         270000.0000  513531.0000  808650.0000  307511.0  4.0500e+06  5.9903e+05  4.5000e+04  402490.7770  2.547e+05               1.381e+06               4.5e+05                        1.764e+06                      2.038e+05                      2.547e+05                      5.387e+05                      6.3e+05                        6.795e+05                      7.552e+05
AMT_ANNUITY                   float64  13672 (4.45%)     12 (0.00%)       0 (0.00%)         0 (0.00%)         16524.0000   24903.0000   34596.0000   307499.0  2.5803e+05  2.7109e+04  1.6155e+03  14493.7373   2.519e+04               3.971e+04               2.25e+04                       4.851e+04                      1.623e+04                      2.519e+04                      2.605e+04                      2.327e+04                      3.62e+04                       3.646e+04
AMT_GOODS_PRICE               float64  1002 (0.33%)      278 (0.09%)      0 (0.00%)         0 (0.00%)         238500.0000  450000.0000  679500.0000  307233.0  4.0500e+06  5.3840e+05  4.0500e+04  369446.4605  2.25e+05                1.206e+06               4.5e+05                        1.764e+06                      1.8e+05                        2.25e+05                       4.815e+05                      6.3e+05                        6.795e+05                      6.75e+05
NAME_TYPE_SUITE               object   7 (0.00%)         1292 (0.42%)     0 (0.00%)         0 (0.00%)         0.0000       0.0000       0.0000       0.0       0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Unaccompanied           Unaccompanied           Unaccompanied                  Unaccompanied                  Unaccompanied                  Unaccompanied                  Unaccompanied                  Unaccompanied                  Family                         Family
NAME_INCOME_TYPE              object   8 (0.00%)         0 (0.00%)        0 (0.00%)         0 (0.00%)         0.0000       0.0000       0.0000       0.0       0.0000e+00  0.0000e+00  0.0000e+00  0.0000       State servant           Working                 Working                        Commercial associate           Working                        Pensioner                      Working                        Working                        Working                        Working
NAME_EDUCATION_TYPE           object   5 (0.00%)         0 (0.00%)        0 (0.00%)         0 (0.00%)         0.0000       0.0000       0.0000       0.0       0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Higher education        Incomplete higher       Secondary / secondary special  Secondary / secondary special  Secondary / secondary special  Secondary / secondary special  Secondary / secondary special  Secondary / secondary special  Secondary / secondary special  Secondary / secondary special
NAME_FAMILY_STATUS            object   6 (0.00%)         0 (0.00%)        0 (0.00%)         0 (0.00%)         0.0000       0.0000       0.0000       0.0       0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Married                 Married                 Married                        Married                        Separated                      Married                        Single / not married           Married                        Married                        Married
NAME_HOUSING_TYPE             object   6 (0.00%)         0 (0.00%)        0 (0.00%)         0 (0.00%)         0.0000       0.0000       0.0000       0.0       0.0000e+00  0.0000e+00  0.0000e+00  0.0000       House / apartment       House / apartment       House / apartment              House / apartment              House / apartment              House / apartment              House / apartment              House / apartment              House / apartment              With parents
REGION_POPULATION_RELATIVE    float64  81 (0.03%)        0 (0.00%)        0 (0.00%)         0 (0.00%)         0.0100       0.0188       0.0287       307511.0  7.2508e-02  2.0868e-02  2.9000e-04  0.0138       0.02461                 0.01863                 0.01522                        0.008019                       0.0105                         0.008866                       0.01863                        0.0105                         0.01885                        0.03076
DAYS_BIRTH                    int64    17460 (5.68%)     0 (0.00%)        307511 (100.00%)  0 (0.00%)        -19682.0000  -15750.0000  -12413.0000   307511.0 -7.4890e+03 -1.6037e+04 -2.5229e+04  4363.9886    -21882                  -14026                  -9905                          -11946                         -10493                         -24264                         -15251                         -14263                         -11179                         -10477
DAYS_EMPLOYED                 int64    12574 (4.09%)     0 (0.00%)        252135 (81.99%)   2 (0.00%)        -2760.0000   -1213.0000   -289.0000     307511.0  3.6524e+05  6.3815e+04 -1.7912e+04  141275.7665  -2987                   -270                    -2691                          -1526                          -656                           365243                         -1984                          -481                           -687                           -1400
DAYS_REGISTRATION             float64  15688 (5.10%)     0 (0.00%)        307431 (99.97%)   80 (0.03%)       -7479.5000   -4504.0000   -2010.0000    307511.0  0.0000e+00 -4.9861e+03 -2.4672e+04  3522.8863   -1.112e+04              -1625                   -4725                          -1513                          -2389                          -87                            -6933                          -1315                          -1491                          -5034
DAYS_ID_PUBLISH               int64    6168 (2.01%)      0 (0.00%)        307495 (99.99%)   16 (0.01%)       -4299.0000   -3254.0000   -1720.0000    307511.0  0.0000e+00 -2.9942e+03 -7.1970e+03  1509.4504    -3984                   -4768                   -2549                          -4392                          -2526                          -4388                          -4396                          -4830                          -2742                          -1625
OWN_CAR_AGE                   float64  62 (0.02%)        202929 (65.99%)  0 (0.00%)         2134 (0.69%)      5.0000       9.0000       15.0000      104582.0  9.1000e+01  1.2061e+01  0.0000e+00  11.9448      4                       1                       NaN                            NaN                            NaN                            NaN                            NaN                            18                             NaN                            NaN
FLAG_MOBIL                    int64    2 (0.00%)         0 (0.00%)        0 (0.00%)         1 (0.00%)         1.0000       1.0000       1.0000       307511.0  1.0000e+00  1.0000e+00  0.0000e+00  0.0018       1                       1                       1                              1                              1                              1                              1                              1                              1                              1
FLAG_EMP_PHONE                int64    2 (0.00%)         0 (0.00%)        0 (0.00%)         55386 (18.01%)    1.0000       1.0000       1.0000       307511.0  1.0000e+00  8.1989e-01  0.0000e+00  0.3843       1                       1                       1                              1                              1                              0                              1                              1                              1                              1
FLAG_WORK_PHONE               int64    2 (0.00%)         0 (0.00%)        0 (0.00%)         246203 (80.06%)   0.0000       0.0000       0.0000       307511.0  1.0000e+00  1.9937e-01  0.0000e+00  0.3995       1                       0                       0                              0                              1                              0                              0                              0                              1                              1
FLAG_CONT_MOBILE              int64    2 (0.00%)         0 (0.00%)        0 (0.00%)         574 (0.19%)       1.0000       1.0000       1.0000       307511.0  1.0000e+00  9.9813e-01  0.0000e+00  0.0432       1                       1                       1                              1                              1                              1                              1                              1                              1                              1
FLAG_PHONE                    int64    2 (0.00%)         0 (0.00%)        0 (0.00%)         221080 (71.89%)   0.0000       0.0000       1.0000       307511.0  1.0000e+00  2.8107e-01  0.0000e+00  0.4495       1                       0                       0                              0                              1                              0                              0                              0                              1                              0
FLAG_EMAIL                    int64    2 (0.00%)         0 (0.00%)        0 (0.00%)         290069 (94.33%)   0.0000       0.0000       0.0000       307511.0  1.0000e+00  5.6720e-02  0.0000e+00  0.2313       0                       0                       0                              0                              0                              0                              0                              0                              0                              0
OCCUPATION_TYPE               object   18 (0.01%)        96391 (31.35%)   0 (0.00%)         0 (0.00%)         0.0000       0.0000       0.0000       0.0       0.0000e+00  0.0000e+00  0.0000e+00  0.0000       NaN                     Drivers                 Laborers                       NaN                            Laborers                       NaN                            Laborers                       NaN                            Managers                       Laborers
CNT_FAM_MEMBERS               float64  17 (0.01%)        2 (0.00%)        0 (0.00%)         0 (0.00%)         2.0000       2.0000       3.0000       307509.0  2.0000e+01  2.1527e+00  1.0000e+00  0.9107       2                       3                       2                              2                              1                              2                              1                              3                              4                              2
REGION_RATING_CLIENT          int64    3 (0.00%)         0 (0.00%)        0 (0.00%)         0 (0.00%)         2.0000       2.0000       2.0000       307511.0  3.0000e+00  2.0525e+00  1.0000e+00  0.5090       2                       2                       2                              2                              3                              2                              2                              3                              2                              2
REGION_RATING_CLIENT_W_CITY   int64    3 (0.00%)         0 (0.00%)        0 (0.00%)         0 (0.00%)         2.0000       2.0000       2.0000       307511.0  3.0000e+00  2.0315e+00  1.0000e+00  0.5027       2                       2                       2                              2                              3                              2                              2                              3                              2                              2
WEEKDAY_APPR_PROCESS_START    object   7 (0.00%)         0 (0.00%)        0 (0.00%)         0 (0.00%)         0.0000       0.0000       0.0000       0.0       0.0000e+00  0.0000e+00  0.0000e+00  0.0000       THURSDAY                MONDAY                  WEDNESDAY                      FRIDAY                         WEDNESDAY                      MONDAY                         FRIDAY                         MONDAY                         TUESDAY                        FRIDAY
HOUR_APPR_PROCESS_START       int64    24 (0.01%)        0 (0.00%)        0 (0.00%)         40 (0.01%)        10.0000      12.0000      14.0000      307511.0  2.3000e+01  1.2063e+01  0.0000e+00  3.2658       17                      10                      9                              10                             15                             17                             9                              13                             12                             13
REG_REGION_NOT_LIVE_REGION    int64    2 (0.00%)         0 (0.00%)        0 (0.00%)         302854 (98.49%)   0.0000       0.0000       0.0000       307511.0  1.0000e+00  1.5144e-02  0.0000e+00  0.1221       0                       0                       0                              0                              0                              0                              0                              0                              0                              0
REG_REGION_NOT_WORK_REGION    int64    2 (0.00%)         0 (0.00%)        0 (0.00%)         291899 (94.92%)   0.0000       0.0000       0.0000       307511.0  1.0000e+00  5.0769e-02  0.0000e+00  0.2195       0                       0                       0                              1                              1                              0                              0                              0                              0                              0
LIVE_REGION_NOT_WORK_REGION   int64    2 (0.00%)         0 (0.00%)        0 (0.00%)         295008 (95.93%)   0.0000       0.0000       0.0000       307511.0  1.0000e+00  4.0659e-02  0.0000e+00  0.1975       0                       0                       0                              1                              1                              0                              0                              0                              0                              0
REG_CITY_NOT_LIVE_CITY        int64    2 (0.00%)         0 (0.00%)        0 (0.00%)         283472 (92.18%)   0.0000       0.0000       0.0000       307511.0  1.0000e+00  7.8173e-02  0.0000e+00  0.2684       0                       0                       1                              0                              0                              0                              0                              0                              0                              0
REG_CITY_NOT_WORK_CITY        int64    2 (0.00%)         0 (0.00%)        0 (0.00%)         236644 (76.95%)   0.0000       0.0000       0.0000       307511.0  1.0000e+00  2.3045e-01  0.0000e+00  0.4211       0                       0                       1                              1                              1                              0                              0                              0                              0                              0
LIVE_CITY_NOT_WORK_CITY       int64    2 (0.00%)         0 (0.00%)        0 (0.00%)         252296 (82.04%)   0.0000       0.0000       0.0000       307511.0  1.0000e+00  1.7955e-01  0.0000e+00  0.3838       0                       0                       0                              1                              1                              0                              0                              0                              0                              0

Exploring bureau.csv
('Total records:', 1716428)
('Total columns:', 17)

                       sub_type         n_distinct            n_miss         n_negative           n_zeros         25%        50%         75%      count         max        mean         min         std         sample_0         sample_1         sample_2         sample_3    sample_4         sample_5         sample_6         sample_7     sample_8     sample_9
name
SK_ID_CURR              int64    305811 (17.82%)    0 (0.00%)         0 (0.00%)          0 (0.00%)         1.8887e+05  278055.0   3.6743e+05  1716428.0  4.5626e+05  2.7821e+05  1.0000e+05  1.0294e+05  226678           158734           202284           275757           308924      298539           220126           180625           152418       134343
SK_ID_BUREAU            int64    1716428 (100.00%)  0 (0.00%)         0 (0.00%)          0 (0.00%)         5.4640e+06  5926303.5  6.3857e+06  1716428.0  6.8435e+06  5.9244e+06  5.0000e+06  5.3227e+05  6173729          6281010          6584010          6680033          5347959     5746640          6356593          6387149          6351262      5829930
CREDIT_ACTIVE           object   4 (0.00%)          0 (0.00%)         0 (0.00%)          0 (0.00%)         0.0000e+00  0.0        0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  Closed           Closed           Closed           Active           Closed      Closed           Closed           Closed           Active       Active
CREDIT_CURRENCY         object   4 (0.00%)          0 (0.00%)         0 (0.00%)          0 (0.00%)         0.0000e+00  0.0        0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  currency 1       currency 1       currency 1       currency 1       currency 1  currency 1       currency 1       currency 1       currency 1   currency 1
DAYS_CREDIT             int64    2923 (0.17%)       0 (0.00%)         1716403 (100.00%)  25 (0.00%)       -1.6660e+03 -987.0     -4.7400e+02  1716428.0  0.0000e+00 -1.1421e+03 -2.9220e+03  7.9516e+02  -1467            -2507            -643             -924             -304        -711             -2742            -405             -1615        -16
CREDIT_DAY_OVERDUE      int64    942 (0.05%)        0 (0.00%)         0 (0.00%)          1712211 (99.75%)  0.0000e+00  0.0        0.0000e+00  1716428.0  2.7920e+03  8.1817e-01  0.0000e+00  3.6544e+01  0                0                0                0                0           0                0                0                0            0
DAYS_CREDIT_ENDDATE     float64  14096 (0.82%)      105553 (6.15%)    1007389 (58.69%)   883 (0.05%)      -1.1380e+03 -330.0      4.7400e+02  1610875.0  3.1199e+04  5.1052e+02 -4.2060e+04  4.9942e+03 -676             -2202            -97               163              NaN        -619             -2374             326              955          1068
DAYS_ENDDATE_FACT       float64  2917 (0.17%)       633653 (36.92%)   1082711 (63.08%)   64 (0.00%)       -1.4890e+03 -897.0     -4.2500e+02  1082775.0  0.0000e+00 -1.0174e+03 -4.2023e+04  7.1401e+02 -676             -2230            -97               NaN             -279        -619             -2374            -160              NaN          NaN
AMT_CREDIT_MAX_OVERDUE  float64  68251 (3.98%)      1124488 (65.51%)  0 (0.00%)          470650 (27.42%)   0.0000e+00  0.0        0.0000e+00  591940.0   1.1599e+08  3.8254e+03  0.0000e+00  2.0603e+05  NaN              0                NaN              NaN              NaN         NaN              NaN              NaN              NaN          NaN
CNT_CREDIT_PROLONG      int64    10 (0.00%)         0 (0.00%)         0 (0.00%)          1707314 (99.47%)  0.0000e+00  0.0        0.0000e+00  1716428.0  9.0000e+00  6.4104e-03  0.0000e+00  9.6224e-02  0                0                0                0                0           0                0                0                0            0
AMT_CREDIT_SUM          float64  236708 (13.79%)    13 (0.00%)        0 (0.00%)          66582 (3.88%)     5.1300e+04  125518.5   3.1500e+05  1716415.0  5.8500e+08  3.5499e+05  0.0000e+00  1.1498e+06  1.114e+05        4.5e+04          2.378e+05        4.5e+05          2.925e+04   1.858e+04        6.75e+05         9.713e+04        2.7e+04      3.6e+04
AMT_CREDIT_SUM_DEBT     float64  226537 (13.20%)    257669 (15.01%)   8418 (0.49%)       1016434 (59.22%)  0.0000e+00  0.0        4.0154e+04  1458759.0  1.7010e+08  1.3709e+05 -4.7056e+06  6.7740e+05  0                0                NaN              6.44e+04         0           0                0                0                2.885e+04    3.502e+04
AMT_CREDIT_SUM_LIMIT    float64  51726 (3.01%)      591780 (34.48%)   351 (0.02%)        1050142 (61.18%)  0.0000e+00  0.0        0.0000e+00  1124648.0  4.7056e+06  6.2295e+03 -5.8641e+05  4.5032e+04  NaN              0                NaN              0                NaN         0                0                NaN              NaN          0
AMT_CREDIT_SUM_OVERDUE  float64  1616 (0.09%)       0 (0.00%)         0 (0.00%)          1712270 (99.76%)  0.0000e+00  0.0        0.0000e+00  1716428.0  3.7567e+06  3.7913e+01  0.0000e+00  5.9377e+03  0                0                0                0                0           0                0                0                0            0
CREDIT_TYPE             object   15 (0.00%)         0 (0.00%)         0 (0.00%)          0 (0.00%)         0.0000e+00  0.0        0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  Consumer credit  Consumer credit  Consumer credit  Consumer credit  Microloan   Consumer credit  Consumer credit  Consumer credit  Credit card  Credit card
DAYS_CREDIT_UPDATE      int64    2982 (0.17%)       0 (0.00%)         1715806 (99.96%)   605 (0.04%)      -9.0800e+02 -395.0     -3.3000e+01  1716428.0  3.7200e+02 -5.9375e+02 -4.1947e+04  7.2075e+02  -676             -1535            -92              -8               -279        -601             -1683            -19              -30          -5
AMT_ANNUITY             float64  40321 (2.35%)      1226791 (71.47%)  0 (0.00%)          256915 (14.97%)   0.0000e+00  0.0        1.3500e+04  489637.0   1.1845e+08  1.5713e+04  0.0000e+00  3.2583e+05  NaN              NaN              NaN              NaN              NaN         NaN              0                NaN              4.076e+04    0

Exploring bureau_balance.csv
('Total records:', 27299925)
('Total columns:', 3)

               sub_type      n_distinct     n_miss         n_negative         n_zeros        25%        50%        75%       count        max        mean        min          std sample_0 sample_1 sample_2 sample_3 sample_4 sample_5 sample_6 sample_7 sample_8 sample_9
name
SK_ID_BUREAU    int64    817395 (2.99%)  0 (0.00%)  0 (0.00%)          0 (0.00%)       5730933.0  6070821.0  6431951.0  2.7300e+07  6842888.0  6.0363e+06  5001709.0  492348.8569  5162830  5115417  5999691  5898774  5797891  6492595  6809852  6053213  6169803  6686363
MONTHS_BALANCE  int64    97 (0.00%)      0 (0.00%)  26688960 (97.76%)  610965 (2.24%) -46.0      -25.0      -11.0       2.7300e+07  0.0       -3.0742e+01 -96.0       23.8645      -26      -39      -69      -25      -36      -1       -43      -27      -15      -30
STATUS          object   8 (0.00%)       0 (0.00%)  0 (0.00%)          0 (0.00%)       0.0        0.0        0.0        0.0000e+00  0.0        0.0000e+00  0.0        0.0000       X        1        X        X        C        C        0        C        C        0

Exploring credit_card_balance.csv
('Total records:', 3840312)
('Total columns:', 23)

                           sub_type        n_distinct           n_miss         n_negative           n_zeros         25%        50%         75%      count         max        mean         min          std   sample_0 sample_1 sample_2   sample_3   sample_4 sample_5   sample_6 sample_7 sample_8   sample_9
name
SK_ID_PREV                  int64    104307 (2.72%)    0 (0.00%)        0 (0.00%)          0 (0.00%)         1.4344e+06  1897122.0  2.3693e+06  3840312.0  2.8435e+06  1.9045e+06  1.0000e+06  536469.4706  2033976    1298413  1590798  1979274    1903431    2022496  2498831    1235207  2837796  2399399
SK_ID_CURR                  int64    103558 (2.70%)    0 (0.00%)        0 (0.00%)          0 (0.00%)         1.8952e+05  278396.0   3.6758e+05  3840312.0  4.5625e+05  2.7832e+05  1.0001e+05  102704.4751  379258     281213   422598   393320     223935     240743   167235     359955   102048   387413
MONTHS_BALANCE              int64    96 (0.00%)        0 (0.00%)        3840312 (100.00%)  0 (0.00%)        -5.5000e+01 -28.0      -1.1000e+01  3840312.0 -1.0000e+00 -3.4522e+01 -9.6000e+01  26.6678      -6         -68      -5       -1         -41        -60      -2         -71      -26      -65
AMT_BALANCE                 float64  1347904 (35.10%)  0 (0.00%)        2345 (0.06%)       2156420 (56.15%)  0.0000e+00  0.0        8.9047e+04  3840312.0  1.5059e+06  5.8300e+04 -4.2025e+05  106307.0310  4.221e+04  0        0        0          1.817e+05  0        1.879e+05  0        0        1.717e+04
AMT_CREDIT_LIMIT_ACTUAL     int64    181 (0.00%)       0 (0.00%)        0 (0.00%)          753823 (19.63%)   4.5000e+04  112500.0   1.8000e+05  3840312.0  1.3500e+06  1.5381e+05  0.0000e+00  165145.6995  225000     67500    135000   0          180000     0        180000     0        90000    90000
AMT_DRAWINGS_ATM_CURRENT    float64  2267 (0.06%)      749816 (19.52%)  1 (0.00%)          2665718 (69.41%)  0.0000e+00  0.0        0.0000e+00  3090496.0  2.1150e+06  5.9613e+03 -6.8273e+03  28225.6886   0          0        NaN      0          9000       0        2250       0        0        0
AMT_DRAWINGS_CURRENT        float64  187005 (4.87%)    0 (0.00%)        3 (0.00%)          3223443 (83.94%)  0.0000e+00  0.0        0.0000e+00  3840312.0  2.2871e+06  7.4334e+03 -6.2116e+03  33846.0773   2601       0        0        0          9000       0        2250       0        0        0
AMT_DRAWINGS_OTHER_CURRENT  float64  1832 (0.05%)      749816 (19.52%)  0 (0.00%)          3078163 (80.15%)  0.0000e+00  0.0        0.0000e+00  3090496.0  1.5298e+06  2.8817e+02  0.0000e+00  8201.9893    0          0        NaN      0          0          0        0          0        0        0
AMT_DRAWINGS_POS_CURRENT    float64  168748 (4.39%)    749816 (19.52%)  0 (0.00%)          2825595 (73.58%)  0.0000e+00  0.0        0.0000e+00  3090496.0  2.2393e+06  2.9688e+03  0.0000e+00  20796.8870   2601       0        NaN      0          0          0        0          0        0        0
AMT_INST_MIN_REGULARITY     float64  312266 (8.13%)    305236 (7.95%)   0 (0.00%)          1928864 (50.23%)  0.0000e+00  0.0        6.6339e+03  3535076.0  2.0288e+05  3.5402e+03  0.0000e+00  5600.1541    2250       0        0        0          9000       0        9338       0        0        4500
AMT_PAYMENT_CURRENT         float64  163209 (4.25%)    767988 (20.00%)  0 (0.00%)          390507 (10.17%)   1.5237e+02  2702.7     9.0000e+03  3072324.0  4.2892e+06  1.0281e+04  0.0000e+00  36078.0850   7200       674.9    NaN      0          9000       8.64     9450       212.4    5823     4500
AMT_PAYMENT_TOTAL_CURRENT   float64  182957 (4.76%)    0 (0.00%)        0 (0.00%)          2172223 (56.56%)  0.0000e+00  0.0        6.7500e+03  3840312.0  4.2783e+06  7.5889e+03  0.0000e+00  32005.9878   4889       0        0        0          9000       0        9450       0        0        4500
AMT_RECEIVABLE_PRINCIPAL    float64  1195839 (31.14%)  0 (0.00%)        2428 (0.06%)       2296167 (59.79%)  0.0000e+00  0.0        8.5359e+04  3840312.0  1.4723e+06  5.5966e+04 -4.2331e+05  102533.6168  4.162e+04  0        0        0          1.74e+05   0        1.796e+05  0        0        1.536e+04
AMT_RECIVABLE               float64  1338878 (34.86%)  0 (0.00%)        109338 (2.85%)     2113816 (55.04%)  0.0000e+00  0.0        8.8899e+04  3840312.0  1.4933e+06  5.8089e+04 -4.2025e+05  105965.3699  4.221e+04  0        0        0          1.817e+05  0        1.861e+05  0        0        1.717e+04
AMT_TOTAL_RECEIVABLE        float64  1339008 (34.87%)  0 (0.00%)        109330 (2.85%)     2113643 (55.04%)  0.0000e+00  0.0        8.8915e+04  3840312.0  1.4933e+06  5.8098e+04 -4.2025e+05  105971.8011  4.221e+04  0        0        0          1.817e+05  0        1.861e+05  0        0        1.717e+04
CNT_DRAWINGS_ATM_CURRENT    float64  44 (0.00%)        749816 (19.52%)  0 (0.00%)          2665718 (69.41%)  0.0000e+00  0.0        0.0000e+00  3090496.0  5.1000e+01  3.0945e-01  0.0000e+00  1.1004       0          0        NaN      0          2          0        1          0        0        0
CNT_DRAWINGS_CURRENT        int64    129 (0.00%)       0 (0.00%)        0 (0.00%)          3229952 (84.11%)  0.0000e+00  0.0        0.0000e+00  3840312.0  1.6500e+02  7.0314e-01  0.0000e+00  3.1903       3          0        0        0          2          0        1          0        0        0
CNT_DRAWINGS_OTHER_CURRENT  float64  11 (0.00%)        749816 (19.52%)  0 (0.00%)          3077688 (80.14%)  0.0000e+00  0.0        0.0000e+00  3090496.0  1.2000e+01  4.8125e-03  0.0000e+00  0.0826       0          0        NaN      0          0          0        0          0        0        0
CNT_DRAWINGS_POS_CURRENT    float64  133 (0.00%)       749816 (19.52%)  0 (0.00%)          2825594 (73.58%)  0.0000e+00  0.0        0.0000e+00  3090496.0  1.6500e+02  5.5948e-01  0.0000e+00  3.2406       3          0        NaN      0          0          0        0          0        0        0
CNT_INSTALMENT_MATURE_CUM   float64  121 (0.00%)       305236 (7.95%)   0 (0.00%)          551467 (14.36%)   4.0000e+00  15.0       3.2000e+01  3535076.0  1.2000e+02  2.0825e+01  0.0000e+00  20.0515      7          33       0        12         56         19       14         9        24       34
NAME_CONTRACT_STATUS        object   7 (0.00%)         0 (0.00%)        0 (0.00%)          0 (0.00%)         0.0000e+00  0.0        0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Active     Active   Active   Completed  Active     Active   Active     Active   Active   Active
SK_DPD                      int64    917 (0.02%)       0 (0.00%)        0 (0.00%)          3686957 (96.01%)  0.0000e+00  0.0        0.0000e+00  3840312.0  3.2600e+03  9.2837e+00  0.0000e+00  97.5157      0          0        0        0          0          0        0          0        0        0
SK_DPD_DEF                  int64    378 (0.01%)       0 (0.00%)        0 (0.00%)          3750972 (97.67%)  0.0000e+00  0.0        0.0000e+00  3840312.0  3.2600e+03  3.3162e-01  0.0000e+00  21.4792      0          0        0        0          0          0        0          0        0        0

Exploring installments_payments.csv
('Total records:', 13605401)
('Total columns:', 8)

                       sub_type      n_distinct        n_miss          n_negative           n_zeros         25%         50%         75%       count         max        mean        min          std    sample_0    sample_1    sample_2    sample_3   sample_4    sample_5    sample_6    sample_7   sample_8   sample_9
name
SK_ID_PREV              int64    997752 (7.33%)  0 (0.00%)     0 (0.00%)           0 (0.00%)         1.4342e+06  1.8965e+06  2.3691e+06  1.3605e+07  2.8435e+06  1.9034e+06  1000001.0  536202.9055  1.4343e+06  1.6140e+06  1.5035e+06  2.6746e+06  2473148.0  1.2894e+06  2.1772e+06  1.1575e+06  1515366.0  1767561.0
SK_ID_CURR              int64    339587 (2.50%)  0 (0.00%)     0 (0.00%)           0 (0.00%)         1.8964e+05  2.7868e+05  3.6753e+05  1.3605e+07  4.5626e+05  2.7844e+05  100001.0   102718.3104  1.4943e+05  1.7820e+05  3.7177e+05  1.2463e+05  355290.0   3.6956e+05  1.3184e+05  1.1488e+05  369258.0   315860.0
NUM_INSTALMENT_VERSION  float64  65 (0.00%)      0 (0.00%)     0 (0.00%)           4082498 (30.01%)  0.0000e+00  1.0000e+00  1.0000e+00  1.3605e+07  1.7800e+02  8.5664e-01  0.0        1.0352       1.0000e+00  1.0000e+00  1.0000e+00  1.0000e+00  0.0        1.0000e+00  1.0000e+00  1.0000e+00  2.0        1.0
NUM_INSTALMENT_NUMBER   int64    277 (0.00%)     0 (0.00%)     0 (0.00%)           0 (0.00%)         4.0000e+00  8.0000e+00  1.9000e+01  1.3605e+07  2.7700e+02  1.8871e+01  1.0        26.6641      5.0000e+00  7.0000e+00  8.0000e+00  1.0000e+00  63.0       5.0000e+00  3.0000e+00  1.0000e+00  15.0       5.0
DAYS_INSTALMENT         float64  2922 (0.02%)    0 (0.00%)     13605401 (100.00%)  0 (0.00%)        -1.6540e+03 -8.1800e+02 -3.6100e+02  1.3605e+07 -1.0000e+00 -1.0423e+03 -2922.0     800.9463    -4.0100e+02 -2.2580e+03 -4.1000e+02 -5.5300e+02 -1816.0    -7.7500e+02 -3.9500e+02 -6.1600e+02 -450.0     -727.0
DAYS_ENTRY_PAYMENT      float64  3039 (0.02%)    2905 (0.02%)  13602496 (99.98%)   0 (0.00%)        -1.6620e+03 -8.2700e+02 -3.7000e+02  1.3602e+07 -1.0000e+00 -1.0511e+03 -4921.0     800.5859    -4.1300e+02 -2.2640e+03 -4.1200e+02 -5.5800e+02 -1829.0    -7.9100e+02 -3.9900e+02 -6.3000e+02 -466.0     -735.0
AMT_INSTALMENT          float64  902539 (6.63%)  0 (0.00%)     0 (0.00%)           290 (0.00%)       4.2261e+03  8.8841e+03  1.6710e+04  1.3605e+07  3.7715e+06  1.7051e+04  0.0        50570.2544   1.1093e+04  2.4050e+04  4.7840e+03  2.0124e+04  7875.0     1.6709e+04  1.1969e+04  1.2441e+04  294150.6   10495.8
AMT_PAYMENT             float64  944235 (6.94%)  2905 (0.02%)  0 (0.00%)           1440 (0.01%)      3.3983e+03  8.1255e+03  1.6108e+04  1.3602e+07  3.7715e+06  1.7238e+04  0.0        54735.7840   1.1093e+04  2.4050e+04  4.7840e+03  2.0124e+04  7875.0     1.6709e+04  1.1969e+04  1.2441e+04  294150.6   10495.8

Exploring previous_application.csv
('Total records:', 1670214)
('Total columns:', 37)

                            sub_type         n_distinct            n_miss         n_negative          n_zeros         25%         50%         75%      count         max        mean         min          std                 sample_0                 sample_1                 sample_2                     sample_3                    sample_4                 sample_5                     sample_6         sample_7                 sample_8                     sample_9
name
SK_ID_PREV                   int64    1670214 (100.00%)  0 (0.00%)         0 (0.00%)          0 (0.00%)        1.4619e+06  1.9231e+06  2.3843e+06  1670214.0  2.8454e+06  1.9231e+06  1.0000e+06  532597.9587  1092395                  1252745                  1426776                  1649070                      1937880                     2786742                  2369053                      2100244          2751684                  1685570
SK_ID_CURR                   int64    338857 (20.29%)    0 (0.00%)         0 (0.00%)          0 (0.00%)        1.8933e+05  2.7871e+05  3.6751e+05  1670214.0  4.5626e+05  2.7836e+05  1.0000e+05  102814.8238  334586                   307326                   164677                   289639                       316386                      325443                   329812                       151568           184899                   428430
NAME_CONTRACT_TYPE           object   4 (0.00%)          0 (0.00%)         0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Revolving loans          Cash loans               Cash loans               Consumer loans               Consumer loans              Cash loans               Consumer loans               Revolving loans  Cash loans               Consumer loans
AMT_ANNUITY                  float64  357959 (21.43%)    372235 (22.29%)   0 (0.00%)          1637 (0.10%)     6.3218e+03  1.1250e+04  2.0658e+04  1297979.0  4.1806e+05  1.5955e+04  0.0000e+00  14782.1373   2250                     NaN                      NaN                      6263                         7556                        NaN                      1.26e+04                     2.025e+04        2.758e+04                1.289e+04
AMT_APPLICATION              float64  93885 (5.62%)      0 (0.00%)         0 (0.00%)          392402 (23.49%)  1.8720e+04  7.1046e+04  1.8036e+05  1670214.0  6.9052e+06  1.7523e+05  0.0000e+00  292779.7624  4.5e+04                  0                        0                        4.364e+04                    7.308e+04                   0                        1.35e+05                     0                4.5e+05                  1.179e+05
AMT_CREDIT                   float64  86803 (5.20%)      1 (0.00%)         0 (0.00%)          336768 (20.16%)  2.4160e+04  8.0541e+04  2.1642e+05  1670213.0  6.9052e+06  1.9611e+05  0.0000e+00  318574.6165  4.5e+04                  0                        0                        5.328e+04                    7.308e+04                   0                        1.35e+05                     4.05e+05         4.916e+05                1.146e+05
AMT_DOWN_PAYMENT             float64  29278 (1.75%)      895844 (53.64%)   2 (0.00%)          369854 (22.14%)  0.0000e+00  1.6380e+03  7.7400e+03  774370.0   3.0600e+06  6.6974e+03 -9.0000e-01  20921.4954   NaN                      NaN                      NaN                      0                            0                           NaN                      0                            NaN              NaN                      2.357e+04
AMT_GOODS_PRICE              float64  93885 (5.62%)      385515 (23.08%)   0 (0.00%)          6869 (0.41%)     5.0841e+04  1.1232e+05  2.3400e+05  1284699.0  6.9052e+06  2.2785e+05  0.0000e+00  315396.5579  4.5e+04                  NaN                      NaN                      4.364e+04                    7.308e+04                   NaN                      1.35e+05                     NaN              4.5e+05                  1.179e+05
WEEKDAY_APPR_PROCESS_START   object   7 (0.00%)          0 (0.00%)         0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       WEDNESDAY                FRIDAY                   WEDNESDAY                SUNDAY                       SATURDAY                    FRIDAY                   TUESDAY                      MONDAY           SATURDAY                 FRIDAY
HOUR_APPR_PROCESS_START      int64    24 (0.00%)         0 (0.00%)         0 (0.00%)          109 (0.01%)      1.0000e+01  1.2000e+01  1.5000e+01  1670214.0  2.3000e+01  1.2484e+01  0.0000e+00  3.3340       12                       16                       11                       7                            10                          16                       21                           17               13                       17
FLAG_LAST_APPL_PER_CONTRACT  object   2 (0.00%)          0 (0.00%)         0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Y                        Y                        Y                        Y                            Y                           Y                        Y                            Y                Y                        Y
NFLAG_LAST_APPL_IN_DAY       int64    2 (0.00%)          0 (0.00%)         0 (0.00%)          5900 (0.35%)     1.0000e+00  1.0000e+00  1.0000e+00  1670214.0  1.0000e+00  9.9647e-01  0.0000e+00  0.0593       1                        1                        1                        1                            1                           1                        1                            1                1                        1
RATE_DOWN_PAYMENT            float64  207033 (12.40%)    895844 (53.64%)   2 (0.00%)          369854 (22.14%)  0.0000e+00  5.1605e-02  1.0891e-01  774370.0   1.0000e+00  7.9637e-02 -1.4979e-05  0.1078       NaN                      NaN                      NaN                      0                            0                           NaN                      0                            NaN              NaN                      0.1858
RATE_INTEREST_PRIMARY        float64  148 (0.01%)        1664263 (99.64%)  0 (0.00%)          0 (0.00%)        1.6072e-01  1.8912e-01  1.9333e-01  5951.0     1.0000e+00  1.8836e-01  3.4781e-02  0.0877       NaN                      NaN                      NaN                      NaN                          NaN                         NaN                      NaN                          NaN              NaN                      NaN
RATE_INTEREST_PRIVILEGED     float64  25 (0.00%)         1664263 (99.64%)  0 (0.00%)          0 (0.00%)        7.1564e-01  8.3510e-01  8.5254e-01  5951.0     1.0000e+00  7.7350e-01  3.7315e-01  0.1009       NaN                      NaN                      NaN                      NaN                          NaN                         NaN                      NaN                          NaN              NaN                      NaN
NAME_CASH_LOAN_PURPOSE       object   25 (0.00%)         0 (0.00%)         0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       XAP                      XNA                      XNA                      XAP                          XAP                         XNA                      XAP                          XAP              XNA                      XAP
NAME_CONTRACT_STATUS         object   4 (0.00%)          0 (0.00%)         0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Approved                 Canceled                 Canceled                 Approved                     Approved                    Refused                  Approved                     Approved         Approved                 Approved
DAYS_DECISION                int64    2922 (0.17%)       0 (0.00%)         1670214 (100.00%)  0 (0.00%)       -1.3000e+03 -5.8100e+02 -2.8000e+02  1670214.0 -1.0000e+00 -8.8068e+02 -2.9220e+03  779.0997     -212                     -217                     -361                     -545                         -1371                       -561                     -625                         -703             -775                     -1021
NAME_PAYMENT_TYPE            object   4 (0.00%)          0 (0.00%)         0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       XNA                      XNA                      XNA                      Cash through the bank        Cash through the bank       XNA                      Cash through the bank        XNA              Cash through the bank    Cash through the bank
CODE_REJECT_REASON           object   9 (0.00%)          0 (0.00%)         0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       XAP                      XAP                      XAP                      XAP                          XAP                         HC                       XAP                          XAP              XAP                      XAP
NAME_TYPE_SUITE              object   7 (0.00%)          820405 (49.12%)   0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Unaccompanied            NaN                      NaN                      NaN                          Other_A                     NaN                      NaN                          NaN              Unaccompanied            Unaccompanied
NAME_CLIENT_TYPE             object   4 (0.00%)          0 (0.00%)         0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Repeater                 Repeater                 Repeater                 Repeater                     Repeater                    Repeater                 New                          Repeater         Repeater                 Repeater
NAME_GOODS_CATEGORY          object   28 (0.00%)         0 (0.00%)         0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       XNA                      XNA                      XNA                      Audio/Video                  Furniture                   XNA                      Audio/Video                  XNA              XNA                      Computers
NAME_PORTFOLIO               object   5 (0.00%)          0 (0.00%)         0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Cards                    XNA                      XNA                      POS                          POS                         XNA                      POS                          Cards            Cash                     POS
NAME_PRODUCT_TYPE            object   3 (0.00%)          0 (0.00%)         0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       walk-in                  XNA                      XNA                      XNA                          XNA                         XNA                      XNA                          x-sell           x-sell                   XNA
CHANNEL_TYPE                 object   8 (0.00%)          0 (0.00%)         0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Credit and cash offices  Credit and cash offices  Credit and cash offices  Country-wide                 Stone                       Credit and cash offices  Country-wide                 Country-wide     Credit and cash offices  Regional / Local
SELLERPLACE_AREA             int64    2097 (0.13%)       0 (0.00%)         762675 (45.66%)    60523 (3.62%)   -1.0000e+00  3.0000e+00  8.2000e+01  1670214.0  4.0000e+06  3.1395e+02 -1.0000e+00  7127.4435    -1                       -1                       -1                       1000                         238                         0                        1000                         154              -1                       168
NAME_SELLER_INDUSTRY         object   11 (0.00%)         0 (0.00%)         0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       XNA                      XNA                      XNA                      Consumer electronics         Furniture                   XNA                      Consumer electronics         Furniture        XNA                      Consumer electronics
CNT_PAYMENT                  float64  49 (0.00%)         372230 (22.29%)   0 (0.00%)          144985 (8.68%)   6.0000e+00  1.2000e+01  2.4000e+01  1297984.0  8.4000e+01  1.6054e+01  0.0000e+00  14.5673      0                        NaN                      NaN                      10                           12                          NaN                      12                           0                24                       10
NAME_YIELD_GROUP             object   5 (0.00%)          0 (0.00%)         0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       XNA                      XNA                      XNA                      middle                       middle                      XNA                      low_normal                   XNA              low_normal               low_normal
PRODUCT_COMBINATION          object   17 (0.00%)         346 (0.02%)       0 (0.00%)          0 (0.00%)        0.0000e+00  0.0000e+00  0.0000e+00  0.0        0.0000e+00  0.0000e+00  0.0000e+00  0.0000       Card Street              Cash                     Cash                     POS household with interest  POS industry with interest  Cash                     POS household with interest  Card X-Sell      Cash X-Sell: low         POS household with interest
DAYS_FIRST_DRAWING           float64  2838 (0.17%)       673065 (40.30%)   62705 (3.75%)      0 (0.00%)        3.6524e+05  3.6524e+05  3.6524e+05  997149.0   3.6524e+05  3.4221e+05 -2.9220e+03  88916.1158   3.652e+05                NaN                      NaN                      3.652e+05                    3.652e+05                   NaN                      3.652e+05                   -599              3.652e+05                3.652e+05
DAYS_FIRST_DUE               float64  2892 (0.17%)       673065 (40.30%)   956504 (57.27%)    0 (0.00%)       -1.6280e+03 -8.3100e+02 -4.1100e+02  997149.0   3.6524e+05  1.3826e+04 -2.8920e+03  72444.8697   3.652e+05                NaN                      NaN                     -514                         -1322                        NaN                     -594                         -553             -745                     -990
DAYS_LAST_DUE_1ST_VERSION    float64  4605 (0.28%)       673065 (40.30%)   678188 (40.60%)    705 (0.04%)     -1.2420e+03 -3.6100e+02  1.2900e+02  997149.0   3.6524e+05  3.3768e+04 -2.8010e+03  106857.0348  3.652e+05                NaN                      NaN                     -244                         -992                         NaN                     -264                          3.652e+05       -55                      -720
DAYS_LAST_DUE                float64  2873 (0.17%)       673065 (40.30%)   785928 (47.06%)    0 (0.00%)       -1.3140e+03 -5.3700e+02 -7.4000e+01  997149.0   3.6524e+05  7.6582e+04 -2.8890e+03  149647.4151  3.652e+05                NaN                      NaN                     -364                         -992                         NaN                     -324                          3.652e+05       -625                     -720
DAYS_TERMINATION             float64  2830 (0.17%)       673065 (40.30%)   771236 (46.18%)    0 (0.00%)       -1.2700e+03 -4.9900e+02 -4.4000e+01  997149.0   3.6524e+05  8.1992e+04 -2.8740e+03  153303.5167  3.652e+05                NaN                      NaN                     -356                         -985                         NaN                     -319                          3.652e+05       -612                     -710
NFLAG_INSURED_ON_APPROVAL    float64  2 (0.00%)          673065 (40.30%)   0 (0.00%)          665527 (39.85%)  0.0000e+00  0.0000e+00  1.0000e+00  997149.0   1.0000e+00  3.3257e-01  0.0000e+00  0.4711       0                        NaN                      NaN                      0                            0                           NaN                      0                            0                1                        0

Exploring sample_submission.csv
('Total records:', 48744)
('Total columns:', 2)

           sub_type       n_distinct     n_miss n_negative    n_zeros        25%       50%       75%    count       max         mean       min          std  sample_0  sample_1  sample_2  sample_3  sample_4  sample_5  sample_6  sample_7  sample_8  sample_9
name
SK_ID_CURR  int64    48744 (100.00%)  0 (0.00%)  0 (0.00%)  0 (0.00%)  188557.75  277549.0  367555.5  48744.0  456250.0  277796.6763  100001.0  103169.5473  262887.0  279679.0  340511.0  256663.0  261967.0  359353.0  364403.0  423087.0  115680.0  370913.0
TARGET      float64  1 (0.00%)        0 (0.00%)  0 (0.00%)  0 (0.00%)  0.50       0.5       0.5       48744.0  0.5       0.5000       0.5       0.0000       0.5       0.5       0.5       0.5       0.5       0.5       0.5       0.5       0.5       0.5

CPU times: user 6min 36s, sys: 16 s, total: 6min 52s
Wall time: 1min 39s

In [7]:
%%time
# save reports
for k, v in ls_report.items():
    print("Saving {}".format(k))
    ls_report[k].to_csv(os.path.join("reports", "report_{}".format(k)))

Saving previous_application.csv
Saving application_test.csv
Saving installments_payments.csv
Saving sample_submission.csv
Saving credit_card_balance.csv
Saving bureau.csv
Saving application_train.csv
Saving POS_CASH_balance.csv
Saving bureau_balance.csv
CPU times: user 14.3 ms, sys: 8.26 ms, total: 22.6 ms
Wall time: 26.1 ms